### ISSUE TITLE
Can't run guestshell on CSR1000v in AWS

### ISSUE THREAD

**Issue by zenvdeluca** [CiscoDevNet/csr_aws_guestshell#1]
Hi,

I can't run guestshell on AWS.  version 16.5.1b (latest) 

hr01-us(config)#iox
                 ^
% Invalid input detected at '^' marker.

hr01-us(config)#
hr01-us#gues
hr01-us#guestshell ena
hr01-us#guestshell enable
 iox feature is not enabled
hr01-us#

**Comment by aradford123** [comment]
I think you need 16.6 which should be out very soon?

**Comment by redercj** [comment]
That's correct.  Guest Shell for CSR will be an EFT (Early Field Trial) in 16.6.
